
import __ASTRO_IMAGE_IMPORT_Z1TTnhq from "/src/assets/img/blog/wordcloud/wc1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FGenerating+Word+Cloud+from+Bengali+Text+using+Python.mdx";
import __ASTRO_IMAGE_IMPORT_2krNkz from "/src/assets/img/blog/typesafe-attr/main.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FTypesafe+Wordpress+Block+Attributes.mdx";
import __ASTRO_IMAGE_IMPORT_Z2bfFOP from "/src/assets/img/project/agrosmart/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fagrosmart.mdx";
import __ASTRO_IMAGE_IMPORT_2c3rJM from "/src/assets/img/project/autoturret/a1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fautoturret.mdx";
import __ASTRO_IMAGE_IMPORT_Z4gbeh from "/src/assets/img/project/instaclone/i1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Finstaclone.mdx";
import __ASTRO_IMAGE_IMPORT_7v8m9 from "/src/assets/img/project/newsflash/main.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fnewsflash.mdx";
import __ASTRO_IMAGE_IMPORT_Z2tmDSs from "/src/assets/img/project/opengl-adventures/g1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fopengl-adventures.mdx";
import __ASTRO_IMAGE_IMPORT_1j0t6u from "/src/assets/img/project/quran-cli/main.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fquran-cli.mdx";
import __ASTRO_IMAGE_IMPORT_Z1RQGIL from "/src/assets/img/project/traffichain/t1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Ftraffichain.mdx";
export default new Map([["/src/assets/img/blog/wordcloud/wc1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FGenerating+Word+Cloud+from+Bengali+Text+using+Python.mdx", __ASTRO_IMAGE_IMPORT_Z1TTnhq], ["/src/assets/img/blog/typesafe-attr/main.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FTypesafe+Wordpress+Block+Attributes.mdx", __ASTRO_IMAGE_IMPORT_2krNkz], ["/src/assets/img/project/agrosmart/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fagrosmart.mdx", __ASTRO_IMAGE_IMPORT_Z2bfFOP], ["/src/assets/img/project/autoturret/a1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fautoturret.mdx", __ASTRO_IMAGE_IMPORT_2c3rJM], ["/src/assets/img/project/instaclone/i1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Finstaclone.mdx", __ASTRO_IMAGE_IMPORT_Z4gbeh], ["/src/assets/img/project/newsflash/main.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fnewsflash.mdx", __ASTRO_IMAGE_IMPORT_7v8m9], ["/src/assets/img/project/opengl-adventures/g1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fopengl-adventures.mdx", __ASTRO_IMAGE_IMPORT_Z2tmDSs], ["/src/assets/img/project/quran-cli/main.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Fquran-cli.mdx", __ASTRO_IMAGE_IMPORT_1j0t6u], ["/src/assets/img/project/traffichain/t1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fproject%2Ftraffichain.mdx", __ASTRO_IMAGE_IMPORT_Z1RQGIL]]);
		